### PR TITLE
fix: Substitute environment variables in profiles only if explicitly opted-in

### LINKED ISSUE #1598: Rustic 0.10.1 fatal parse error due to special characters in password.
I have several machines with Rustic running as backup program.
Each have separate s3 buckets with separate passwords.

On one of my machines following the update to 0.10.1 I can no longer run any commands.
It stops with the following error message
`error: rustic-rs fatal error: parse error: No such variable: $m`

When checking the config I noticed that the last 2 characters of the password are the last 2 characters in the error message.

None of my other machines are giving errors.
I have downgraded to 0.10.0 which is not giving me this error.

Part of the config
```
[global]
log-level = "info"
log-file = "/var/opt/rustic/archive.log"

[repository]
repository = "opendal:s3"
password = "<rest of password>W*$m"
```

### PR DESCRIPTION
**Pull request by rdelaage**
Hi!

This PR fix the regression introduced in #1577 by adding an opt-in flag for environment variable substitution in profile files. Users can still use `$` in their file if they enable substitution by escaping them (`\$`).

This PR closes #1598 and #942

### CODE REVIEW

File: src/config.rs [hunk 1]
```diff
@@ -120,16 +126,20 @@ impl RusticConfig {
...
                 )
-            })?;
+                .map_err(|e| {
+                    abscissa_core::error::context::Context::new(
+                        FrameworkErrorKind::ParseError,
+                        Some(Box::new(e)),
+                    )
+                })?
+            } else {
+                std::fs::read_to_string(AbsPathBuf::canonicalize(path)?)?
```
Comment (aawsome) [inline src/config.rs]: maybe read this to a now variable and use this in the if and else branch?

**Review by aawsome — APPROVED** [review]
LGTM! Thanks a lot for the fast PR @rdelaage
